main: minealex.tchat.TChat
version: 4.1.3
name: TChat
author: Mine_Alex
api-version: 1.13

depend: [PlaceholderAPI]

commands:
  tchat:
    description: Reload the plugin
    aliases:
      - chat
  chatcolor:
    description: Open's the chatcolor menu
  channel:
    description: Join/leave a channel
  msg:
    description: Sends a private message
  reply:
    description: Reply to a private message
  chatclear:
    description: Clear's the chat
  mutechat:
    description: Mute the chat
  ping:
    description: View player ping
  broadcast:
    description: Send a message to all players
  ignore:
    description: Ignore a player
  poll:
    description: Create or vote for a poll
  warning:
    description: Send a message to all players
  rules:
    description: View the server rules
  print:
    description: Send a raw message
  announcement:
    description: Send a message to all players
  autobroadcast:
    description: Start or stop autobroadcast system
  plugin:
    description: View information from concrete plugin
  bannedcommands:
    description: Add/remove banned commands
  helpop:
    description: Get help from the staff
  showitem:
    description: Show the item in your hand
  list:
    description: View all online players
  calculator:
    description: Calculate math operations
  player:
    description: Show player information
  server:
    description: Shows server information
  socialspy:
    description: Configure social spy options inside Minecraft
  commandtimer:
    description: Add or remove command timers
  nick:
    description: Change the username
  seen:
    description: View player information
  realname:
    description: Show the realname
  stafflist:
    description: Show the staff list
  bannedwords:
    description: List all banned words
  mute:
    description: Mute other players
  logs:
    description: View logs

permissions:
  tchat.admin.command.logs:
    description: Permission to use logs command
  tchat.admin.mute:
    description: Permission to use mute command
  tchat.admin.command.bannedwords:
    description: Permission to use bannedwords command
  tchat.command.stafflist:
    description: Permission to use stafflist command
  tchat.staff:
    description: Permission to show you in stafflist
  tchat.realname:
    description: Permission to use realname command
  tchat.admin.command.seen:
    description: Permission to use seen command
  tchat.command.seen:
    description: Permission to use seen command
  tchat.nick:
    description: Permission to use nick command
  tchat.admin.commandtimer:
    description: Permission to use commantimer command
  tchat.admin.command.social-spy:
    description: Permission to use socialspy command
  tchat.admin.server:
    description: Permission to use server command
  tchat.admin.player:
    description: Permission to use full player command
  tchat.player:
    description: Permission to use player command
  tchat.admin.calculator:
    description: Permission to use calculator command
  tchat.admin.list:
    description: Permission to use list command
  tchat.admin.helpop:
    description: Permission to receive helpop messages
  tchat.helpop:
    description: Permission to use helpop command
  tchat.admin.bannedcommands:
    description: Permission to use bannedcommands command
  tchat.admin.plugin:
    description: Permission to use plugin command
  tchat.admin.announcement:
    description: Permission to use announcement command
  tchat.rules:
    description: Permission to use rules command
  tchat.admin.print:
    description: Permission to use print command
  tchat.ignore:
    description: Permission to use ignore command
  tchat.admin.broadcast:
    description: Permission to use broadcast command
  tchat.ping:
    description: Permission to use ping command
  tchat.chatcolor.menu:
    description: Permission to open the chatcolor menu
  tchat.admin:
    description: Admin permission
  tchat.reload:
    description: Permission to reload the plugin
  tchat.version:
    description: Permission view the version of the plugin
  tchat.bypass.anticap:
    description: Permission to bypass the anti cap system
  tchat.bypass.command_blocker.tab:
    description: Permission to bypass tab command blocker
  tchat.bypass.command_blocker.command:
    description: Permission to open the chatcolor menu
  tchat.bypass.banned_words:
    description: Permission to bypass banned words system
  tchat.color.all:
    description: Permission to use all colors in chat
  tchat.color.*:
    description: Permission to use colors in chat
  tchat.chatcolor.all:
    description: Permission to use all chat colors
  tchat.chatcolor.*:
    description: Permission to use chat colors
  tchat.channel.all:
    description: Permission to use all channels
  tchat.channel.*:
    description: Permission to use channels